### ISSUE TITLE
condition based on build description

### ISSUE THREAD

**Issue by InvalidCast44** [jenkinsci/build-history-manager-plugin#128]
### What feature do you want to see added?

hi!

the way we would work:
- when we decide to use a build for a customer, we manually set the build description "use by customer x". it may not be the last successful build
- if a successful build has NO description and is too old, then it can be automatically deleted

the too old part is good, but i can't manage to get the description part
i guess there can be a token macro that can gives me it, but i can't find it
![Capture d'écran 2024-06-07 111936](https://github.com/jenkinsci/build-history-manager-plugin/assets/28800506/85a22188-6a47-4901-99a5-b372552b9e56)
in this case, when the "too old" condition is met, only build 154 should be kept

thanks

**Comment by damianszczepanik** [comment]
Take a look and review https://github.com/jenkinsci/build-history-manager-plugin/pull/129

**Comment by InvalidCast44** [comment]
amazing! thanks a lot
did i understand you want me to review? if so i don't think i can sorry
when can we expect a new version please?

**Comment by damianszczepanik** [comment]
Should be released soon
