### ISSUE TITLE
delete builds if a certain parameter is true or matches a value

### ISSUE THREAD

**Issue by briceburg** [jenkinsci/build-history-manager-plugin#31]
I have a parameterized job for running running taurus tests. It is triggered by other jobs that pass in paramaters specific to the test to be run. E.g. a smoke test, a large load test, a small load test, etc -- and thus functions as a test coordinator and handles locking, reporting, etc. etc. in a single place. 

We have a scheduled job that triggers our test runner job telling it to run a smoke test every 5 minutes. 

As such, we are getting **a lot** of build history.  these scheduled smoke tests builds **don't need to be stored**. but we'd like to store the manually run builds. 

A boolean parameter is used to differentiate between the manual and scheduled tests, e.g.

```
parameters {
    booleanParam(name: 'ENABLE_HISTORY', defaultValue: true, description: 'Check to preserve build history.')
    ...
```

and we pass `ENABLE_HISTORY` as false on scheduled builds.

Is it possible to use this plugin to match this condition? I see the Token macro implementation but am confused as to how it works / don't see any examples.

Many thanks!

**Comment by briceburg** [comment]
I was able to look more closely at the implementation and figure things out.

the following pipeline will work:

```
pipeline {
    agent any

    options {
        buildDiscarder(BuildHistoryManager([
            [
                conditions: [
                    TokenMacro(template: '"${ENABLE_HISTORY}"', value: '"false"')
                ],
                actions: [DeleteBuild()],
                continueAfterMatch: false
            ],
            [
                continueAfterMatch: false,
                matchAtMost: 24
            ],
            [
                actions: [DeleteBuild()]
            ]
        ]))
    }

    parameters {
        booleanParam(
          name: 'ENABLE_HISTORY', 
          defaultValue: true, 
          description: 'Check to preserve build.'
        )
    }

    stages {
        stage('Demo') {
            steps {
                echo "Hello!"
            }
        }
    }
}
```

In addition, I opened a PR #2  that includes this example if you'd like to add to the docs. Thanks! This has been a very useful plugin.

**Comment by damianszczepanik** [comment]
@briceburg I have left some comments, please review and consider improvement to make this example clear to understand
