### ISSUE TITLE
Expressions for conditions

### ISSUE THREAD

**Issue by Frettman** [jenkinsci/build-history-manager-plugin#57]
### Feature Request

I have a pipeline that can basically execute two kinds of builds (snapshots and releases) and I can distinguish them via a job parameter (empty string -> snapshot; anything else -> release). I'd like to keep a certain amount of builds for each kind of build.
The only condition I could use for something like this seems to be the `TokenMacro`. So this is the closest I could get to what I would need:
```
        [
          conditions: [TokenMacro(template: '${RELEASE_VERSION}', value: '')],
          matchAtMost: 2,
          continueAfterMatch: false
        ],
        [
          matchAtMost: 2,
          continueAfterMatch: false
        ],
        [
          actions: [DeleteBuild()]
        ]
```
The first rule properly matches all snapshot builds. But the problem is, that I don't have a fitting condition for the second rule which should only match release builds. So, the first rule preserves two snapshot builds, but release builds will eventually be flushed out. Unfortunately neither the Token Macro plug-in nor the `TokenMacro` condition provide anything but a strict "equals".

I have tried to set an environment variable via the `environment` block (I'm using the declarative pipeline syntax btw) based on the job parameter `RELEASE_VERSION` to two simple values that I could compare, but it seems the token macro can't pick it up. I tried `'${IS_RELEASE}'` and `'${ENV,var="IS_RELEASE"}'`. Do you know, if this should work and I just did something wrong?

While having the full power of Groovy would be nice to create expressions (e.g. by reusing Jenkins' `when` conditions or maybe via a closure, if that's even technically feasible), at least for my use case an additional `not`-flag in the `TokenMacro` condition that turns it into a "not equals" would already be enough.

Unless there's something else that I'm missing?

**Comment by damianszczepanik** [comment]
Would follow with TokenMacro features and then I would recommend to read manual how to use compare "operator" for that plugin. Check wiki/readme for that plugin.

If you have Groovy I don't understand why can't you use if - else expression to make this job properly

**Comment by Frettman** [comment]
I have read the documentation of the [Token Macro plugin](https://plugins.jenkins.io/token-macro/). There is unfortunately nothing about comparisons; it only replaces tokens with text, as far as I can see.
The `TokenMacro` condition looks at the `RELEASE_VERSION` of *each previous* build. The Groovy of my job can only access the *current* build. So I don't see how I could use Groovy here.

**Comment by damianszczepanik** [comment]
Generally Groovy can access any build but only when you allow for this. Otherwise you have limited possibility to make this operation

**Comment by Frettman** [comment]
Well, I'd ask why you didn't even consider the simple not-equals in `TokenMacro`, but I've written my own plug-in by now, so I won't bother.

**Comment by damianszczepanik** [comment]
You can prepare PR with that change if you think this is valuable
