### ISSUE TITLE
Build cause as a condition

### ISSUE THREAD

**Issue by oalagtash** [jenkinsci/build-history-manager-plugin#60]
### What feature do you want to see added?

Is it possible to add a build cause condition?

The actual use case is:
I have builds that runs every night. 
I want to abort some of them, then delete them.
So if the build result is **aborted** and the build cause/trigger is **TimerTriggerCause**, it should be deleted.

**Comment by damianszczepanik** [comment]
Interesting case, I will add this into configuration. First add following to your Jenkins, make sure you are triggered job the way you expect and tell me result of the code

```groovy
boolean isCausedBy(String causeClassName) {
    for (String cause in currentBuild.getBuildCauses()) {
        // dependency https://plugins.jenkins.io/pipeline-utility-steps/
        net.sf.json.JSONObject jsonCause = readJSON text: cause.toString()
        if (causeClassName == jsonCause._class) {
            return true
        }
    }
    return false
}

node("built-in") {
    properties([
        pipelineTriggers([cron('H/5 * * * *')])
    ])

    String buildCauseClassName = "hudson.triggers.TimerTrigger\$TimerTriggerCause"

    stage("Hello") {
        echo "Started by trigger: " + isCausedBy(buildCauseClassName)
    }
}
```

**Comment by ljubac** [comment]
Hi  
Nice work.
Please could you  provide an example for conditions[ ] to identify builds that are successful and build case is time trigger.

**Comment by damianszczepanik** [comment]
Several examples should be helpful https://github.com/jenkinsci/build-history-manager-plugin/wiki
