### ISSUE TITLE
Matching Result.NOT_BUILT

### ISSUE THREAD

**Issue by ao-apps** [jenkinsci/build-history-manager-plugin#69]
### What feature do you want to see added?

Is it possible to add a match to [BuildResultCondition.java](https://github.com/jenkinsci/build-history-manager-plugin/blob/master/src/main/java/pl/damianszczepanik/jenkins/buildhistorymanager/model/conditions/BuildResultCondition.java) corresponding to the Jenkins [Result.NOT_BUILT](https://javadoc.jenkins-ci.org/hudson/model/Result.html#NOT_BUILT)?

I would like to be able to select these for specific clean-up rules, too.

Thank you,
\- Dan

**Comment by ao-apps** [comment]
We have submitted PR #70 to fulfill this request.

**Comment by damianszczepanik** [comment]
That was intentional not to support this case as I could not find any reasonable scenario for which this result makes sense.

Share more details what is your scenario.

**Comment by ao-apps** [comment]
Our builds do get NOT_BUILT status on a routine basis.  We use both `disableConcurrentBuilds(abortPrevious: true)` and `quietPeriod(...)`.  We have builds triggered by both git commit hooks as well as cross-project build triggers (following dependency hierarchy).

When a build is in the quiet period, and another build is triggered, the first build is canceled and remains as NOT_BUILT result.

NOT_BUILT results can carry useful information about what triggered the build, even though the build never executed.

We would like to have control over this result status in a consistent manner with the others.

**Comment by ao-apps** [comment]
Thank you for merging #70  We'll work on a separate PR for the null state.

**Comment by ao-apps** [comment]
I've noted that there are places in the Jenkins code that specifically check for null status, confirming it is appropriate to do so.  For example: https://github.com/jenkinsci/jenkins/blob/e27b310065b3c036b5fc9d123f1d1d99d3058c00/core/src/main/java/hudson/model/ResultTrend.java#L164

**Comment by damianszczepanik** [comment]
Exactly, so your code should make this checking as well to avoid NPE

**Comment by ao-apps** [comment]
Implemented as PR#72.

Thank you.

**Comment by ao-apps** [comment]
![Screenshot_20230412_214216](https://user-images.githubusercontent.com/20825951/231634689-29ad8ec5-2363-4dde-8a90-20288b5865e4.png)

We confirm this new functionality is working well for our builds.  We keep the most recent NOT_BUILT (for superseded builds), the most recent ABORTED (when our scripts detect a dependency not ready), and fifty success/unstable/failure.

Thank you again for supporting this Jenkins plug-in.
