### ISSUE TITLE
Actions: mark the build to be kept forever (Missing source code)

### ISSUE THREAD

**Issue by nurgul212** [jenkinsci/build-history-manager-plugin#81]
### Describe your use-case which is not covered by existing documentation.

Hello,

In **Actions** section of README.md, you mentioned that `Plugin can: mark the build to be kept forever`. However, upon reviewing the source code, I couldn't locate any implementation related to this feature.

I would greatly appreciate it if you could clarify this matter and provide guidance regarding the missing source code.

Thank you.
Nurgul

**Comment by damianszczepanik** [comment]
This feature is not a plugin part. You can open the build and update properties. This is available even without the plugin
